# Generated by Django 5.2.4 on 2025-08-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product_rating_alter_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('living', 'Living Room'), ('bedroom', 'Bedroom'), ('dining', 'Dining & Kitchen')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
